name: Build D7 Miner APK
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build with Buildozer
      uses: ArtemSerebrennikov/buildozer-action@v1
      id: buildozer
      with:
        command: buildozer android debug
        buildozer_version: stable

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: D7-Miner-Debug-APK
        path: bin/*.apk
